//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthAssessment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceLine
    {
        public long InvoiceLineId { get; set; }
        public long InvoiceId { get; set; }
        public double Qty { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public decimal LineTotal { get; set; }
    
        public virtual Invoice Invoice { get; set; }
    }
}
